version: "3"
services:
  nginx:
    image: openresty/openresty:alpine-amd64
    ports:
      - "80:80"
      - "81:81"
    volumes:
      - /etc/xray/default.conf:/etc/nginx/conf.d/default.conf
  xray:
    image: xray:v1.5.0
    ports:
      - 443:443
    volumes:
      - /etc/xray:/etc/xray
